services:
  - type: web
    name: osjs
    env: node
    plan: free
    buildCommand: |
      npm install
      npm run build
    startCommand: npm run serve
    envVars:
      - key: NODE_ENV
        value: production
